package services

const (
	NOT_FOUND     = "NOT_FOUND"
	PR_EXISTS     = "PR_EXISTS"
	INVALID_INPUT = "INVALID_INPUT"
	PR_MERGED     = "PR_MERGED"
	NOT_ASSIGNED  = "NOT_ASSIGNED"
	NO_CANDIDATE  = "NO_CANDIDATE"
	TEAM_EXISTS   = "TEAM_EXISTS"
)
